### ISSUE TITLE
Equinox Filter Not Working

### ISSUE THREAD

**Issue by adam-hartshorne** [jamielohoff/graphax#4]
Using JAX v0.4.35, the following equinox example from the code repo doesn't work correctly, It looks like the vmap'ing isn't working correctly, as if you change the leading dim from 64 to 1, it does work (but any batch size != 1, causes a problem). 

```
key = jax.random.PRNGKey(42)
model = eqx.nn.MLP(10, 5, 64, 3, activation=jnp.tanh, key=key)

def loss_fn(model, x, y):
    return jnp.mean((jax.vmap(model)(x) - y) ** 2)

x = jnp.ones((64, 10))
y = jnp.ones((64, 5), dtype=jnp.int32)

jacve_res = filter_jacve(loss_fn, order="rev")(model, x, y)
jax_res_fn = eqx.filter_grad(loss_fn)
jax_res = jax_res_fn(model, x, y)
assert(tree_allclose(jacve_res, jax_res))
```
producing the following errors

Traceback (most recent call last):
  File "/media/adam/shared_folder/PycharmProjects/rigflow/graphax_test.py", line 55, in <module>
    jacve_res = filter_jacve(loss_fn, order="rev")(model, x, y)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/equinox_bindings.py", line 38, in __call__
    return fun_jacve(diff_x, nondiff_x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/equinox_bindings.py", line 33, in fun_jacve
    return eqx_jacve(self._fun, argnums=_argnums, **self._gradkwargs)(_x, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/equinox_bindings.py", line 91, in wrapped
    out = vertex_elimination_jaxpr(closed_jaxpr.jaxpr, 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/core.py", line 681, in vertex_elimination_jaxpr
    num_mul, num_add = _eliminate_vertex(vertex, jaxpr, graph, transpose_graph, iota, vo_vertices)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/core.py", line 359, in _eliminate_vertex
    edge_outval = _post_val * _pre_val
                  ~~~~~~~~~~^~~~~~~~~~
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/sparse/tensor.py", line 119, in __mul__
    return _mul(self, _tensor)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/sparse/tensor.py", line 368, in _mul
    res = _mixed_mul(_lhs, _rhs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/graphax/sparse/tensor.py", line 1179, in _mixed_mul
    new_val = lax.dot_general(lhs.val, rhs.val, dimension_numbers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/jax/_src/lax/lax.py", line 1105, in dot_general
    return dot_general_p.bind(lhs, rhs,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/jax/_src/core.py", line 438, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/jax/_src/core.py", line 442, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/jax/_src/core.py", line 955, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/jax/_src/dispatch.py", line 91, in apply_primitive
    outs = fun(*args)
           ^^^^^^^^^^
TypeError: dot_general requires contracting dimensions to have the same shape, got (1,) and (64,).

**Comment by jamielohoff** [comment]
Hey Adam, thanks! Yes the equinox filter function needs some work. This is not an easy fix. I will attempt to fix this as soon as I find the time.

**Comment by adam-hartshorne** [comment]
Is support for equinox modules still broken?

**Comment by jamielohoff** [comment]
Hi Adam,
yes, I have not yet fixed this but I will try to do it soon. The equinox API has changed quite a bit since I implemented the first interface so this takes some time :)
